### ISSUE TITLE
Heroku Giveaway Log

### ISSUE THREAD

**Issue by bonxz** [Vedza/NitroSniperGo#71] opened 2021-01-04 15:29 UTC
Hey,
![buggy](https://user-images.githubusercontent.com/61289944/103550839-c5ce4000-4ea9-11eb-938c-03853c67c00d.png)

Something is still wrong with the giveaways. He spams in seconds the notifications to my webhook that he has won a giveaway although in the channel is not even something. Have it controlled.

Among other things, I get a websocket error when starting the app although he apparently logs in correctly. 
Also you can't see the asci text with the "DiscordSniper" or how many accounts he is logged in with and how many servers he sniped on.

**Comment by Vedza** [comment] 2021-01-04 15:36
I'm working on giveaway issue rn even if I can't reproduce the bug.
I don't know about the print, I can see it myself.
Btw there are 2 tokens that doesn't work on your screenshot.

**Comment by bonxz** [comment] 2021-01-04 15:40
I only used the main token in the settings and left the alt tokens blank. Could this be the reason?

**Comment by Vedza** [comment] 2021-01-04 15:42
Yeah this is why

**Comment by bonxz** [comment] 2021-01-04 15:44
> 
> 
> Yeah this is why you have this error

Then there should be another option if you don't enter Alt Tokens to turn it off.

And additionally there should be an option that you can decide if you sniped with the main token or not. And you only use it to activate the codes

**Comment by bonxz** [comment] 2021-01-04 19:11
Have discovered another error. Have in the settings Giveaway Sniper off and Nitro Giveaways also off and still get in the log info about how he won a giveaway. (Spams this text again)

**Comment by Vedza** [comment] 2021-01-04 19:29
This is not a new error, the sniper tell you if you won a giveaway even if it doesn't join any.
It's fixed now but the bot will only tell you if the main account won a giveaway, so I must find a solution to fix that.

**Closed by Vedza** 2021-01-04 19:29 UTC
